### ISSUE TITLE
error can you help me?

### ISSUE THREAD

**Issue by icansc187** [osmanfurkan115/WorldGuardGUI#17]
[05:27:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wggui' in plugin WorldGuardGUI v1.1.2at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]
at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_13_R2.IChatBaseComponent field org.bukkit.cra ftbukkit.v1_13_R2.inventory.CraftMetaItem.displayName to java.lang.Stringat jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
at jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:?]at java.lang.reflect.Field.set(Field.java:780) ~[?:?]at me.heymrau.worldguardguiplugin.gui.builder.item.BaseItemBuilder.name(BaseItemBuilder.java:117) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
at me.heymrau.worldguardguiplugin.inventories.MainInventory.open(MainInventory.java:35) ~[?:?]at me.heymrau.worldguardguiplugin.commands.WGGuiCommand.onCommand(WGGuiCommand.java:33) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-2148-d.jar:git-Spigot-1a3504a-06534f2]... 15 more

**Comment by osmanfurkan115** [comment]
I just released a new version. Can you try that out? [Release](https://github.com/osmanfurkan115/WorldGuardGUI/releases/tag/1.1.2)
